<a href="https://colab.research.google.com/github/theoYe/LearnPytorch/blob/master/01Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0. Pytorch 安装及环境配置


In [1]:
import torch
print(torch.cuda.is_available())      
print(torch.rand(2,2))  

True
tensor([[0.6276, 0.8159],
        [0.7951, 0.0485]])


>如果你返回false, 请打开Runtime -> change runtime type , 把第二行换为GPU

# 1. Tensors
*Tensor* 就是存储数据的容器, 你可以把他当成多维数组, Tensor有以下要点
1. 每个Tensor都有对应的秩(rank), 如: 一个标量的秩的是0, 向量的秩是1 , 矩阵的秩是2
 




## 1.1 创建Tensor

In [0]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

我们可以利用torch中提供的函数来创建Tensor , 有以下常用的函数
- zeros()
- rand()
- ones()


In [0]:
a = torch.zeros(2,1)
b = torch.rand(2,2)
c = torch.ones(1,2)

## 1.2 Tensor的存放位置

tensor默认存在于CPU中

In [0]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

Tensors 可以存在于CPU或者GPU中,而且可以使用 `to()`函数来在两个设备之间进行复制

In [0]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

## 1.3 Tensor 常用操作
我们有时需要对Tensor做出一些操作,例如最大值等, Tensor常用的操作如下
>注意, 执行这些操作时, 一般我们仍然会得到一个tensor , 例如max()获取最大值, 我们可能会得到一个一维的tensor值, 如果要转化成标准的python数据类型,使用`item()`来进行转哈
- max(): 获取tensor中最大值
- item(): 将数据转化为标准的python数据类型
- argmax()

In [0]:
torch.rand(2,2).max()

tensor(0.9664)

In [0]:
torch.rand(2,2).max().item()

0.7825084328651428

有时, 我们需要将tensor的类型改变, 例如下面将`LongTensor`转化为`FloatTensor`

In [0]:
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [0]:
float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
float_tensor.type()


'torch.LongTensor'

### 1.3.2 节省空间
绝大多数操作tensor的函数在返回tensor的时候都会建立一个新的tensor来存储数据. 如果你想节省内存, 尝试使用`in place`函数, 如果存在的话, 它的名字是原函数加上一个`_`(下划线), 例如下面的代码

In [2]:
random_tensor = torch.rand(2,2)
random_tensor.log2()


tensor([[-0.1867, -2.2412],
        [-0.4459, -2.7749]])

In [3]:
random_tensor.log2_()

tensor([[-0.1867, -2.2412],
        [-0.4459, -2.7749]])

**也就是说, 带`_`时, 会直接改变原tensor的值**

In [16]:
random_tensor = torch.rand(2,2)
print(random_tensor)
print(random_tensor.log2_())
print(random_tensor)

tensor([[0.0695, 0.5779],
        [0.1967, 0.4233]])
tensor([[-3.8479, -0.7912],
        [-2.3461, -1.2404]])
tensor([[-3.8479, -0.7912],
        [-2.3461, -1.2404]])


In [18]:
random_tensor = torch.rand(2,2)
print(random_tensor)
print(random_tensor.log2())
print(random_tensor)

tensor([[0.9058, 0.3694],
        [0.5933, 0.4879]])
tensor([[-0.1428, -1.4366],
        [-0.7531, -1.0355]])
tensor([[0.9058, 0.3694],
        [0.5933, 0.4879]])


### 1.3.3 重塑tensor
一个常用的操作就是重塑tensor, 例如当你训练神经网络时, 你的神经网络层需要有些不同的输入时. 举个例子, MNIST的手写识别数据集是一个28x28的图片集, 但是它的打包方式却是 784长度的数组, 为了使用这个网络, 我们要把它变成一个1x28x28的tensor,(1代表channel的个数,通常包含3个(RGB), 因为MNIST是灰度图, 所以只有一个), 我们可以使用下面两个函数
- `view()`
- `reshape()`

>view 与reshape 有以下两个区别
>1. view会使用与原数据同样的内存空间, 也就是说改变view (或者改变原tensor), 会使得原tensor(或者view)改变, 而reshape在某些情况下会返回原tensor的复制版本
>2. 当tensor的内存数据不是连续存储时(`non-contiguous`), 会出错




In [0]:
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1,28,28)
viewed_tensor.shape


torch.Size([1, 28, 28])

In [0]:
reshaped_tensor= flat_tensor.reshape(1,28,28)
reshaped_tensor.shape


torch.Size([1, 28, 28])

In [0]:
t = torch.tensor([[1,1,1],[2,2,2]])
tvs = t.view(3,2)
tvs[0][0] = 2
t


tensor([[2, 1, 1],
        [2, 2, 2]])

In [0]:
t = torch.tensor([[1,1,1],[2,2,2]])
tvs = t.reshape(3,2)
tvs[0][0] = 2
t


tensor([[2, 1, 1],
        [2, 2, 2]])

我们可以使用[]中括号索引的方式来改变tensor中的值

In [0]:
x[0][0] = 5
x


tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

### 1.3.4 改变dimension的顺序
我们有时想要改变维度的顺序, 例如我们经常这么存储一个图片**[height, width,channel]**, 但是PyTorch是这么来处理的**[channel , height,width]**
可是就可以使用`permute()`函数来处理顺序
>permute 接收一个元组, 函数参数为维度的索引值


In [22]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])

## 1.4 Tensor Broadcasting
从Numpy中继承而来, `broadcasting`允许你在一个tensor和另一个更小的tensor之间进行操作,在下面两种情况下,你可以在两个tensor之间进行广播,从最后一个维度往后传播:
- 两个tensor的维度相同
- 某一个tensor的维度是1

例如我们不能把一个大小为[2,2]的tensor 和[3,3]的tensor相加, 我们会得到如下错误
```python
The size of tensor a (2) must match the size of
tensor b (3) at non-singleton dimension 1
```

但是我们可以将一个 [1,3]的tensor添加到[3,3]的tensor中

### 参考资料
Contigious vs non-contigious tensor:https://discuss.pytorch.org/t/contigious-vs-non-contigious-tensor/30107
